[tool.black]
line-length = 79
target-version = ['py38']
skip-magic-trailing-comma = true
include = '\.pyi?$'

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
ensure_newline_before_comments = true
use_parentheses = true
skip_gitignore = true
skip_glob = ['venv']
known_standard_library = ['typing']
