name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coveralls

      - name: Run flake8
        run: |
          python -m flake8 conjector/
      - name: Run black
        run: |
          python -m black --line-length 79 --check conjector/
      - name: Run mypy
        run: |
          python -m mypy conjector/
      - name: Run bandit
        run: |
          python -m bandit conjector/ -r
      - name: Run tests
        run: |
          python -m coverage run --source=conjector -m pytest
          python -m coverage lcov --fail-under=80
      - name: Send results to coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-python-${{ matrix.python-version }}
          parallel: true
          path-to-lcov: ./coverage.lcov

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Finish coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
